봇 애플리케이션 만들기 페이지 번역
coding-1ab/korean-guide pull request #21
Opened 2021-09-02 00:53 UTC by mswgen

2021-09-02 09:12 UTC, abiriadev requested changes
63줄 `"es2021"` 을 원본과 같이 바꿔주세요

2021-09-02 09:12 UTC, abiriadev commented on guide/preparations/setting-up-a-linter.md
> +		"es2021": true
원본 가이드와 내용이 다릅니다!

설정 파일과 관련 내용은 그대로 유지해 주세요!

2021-09-02 09:15 UTC, abiriadev requested changes
삭제된 줄을 추가해 주세요

2021-09-02 09:15 UTC, abiriadev commented on guide/preparations/setting-up-a-linter.md
> -* [Sublime Text](https://www.sublimetext.com/)는 코드를 쓰고 읽기 쉬운 또다른 유명한 에디터 입니다.
`Sublime Text` 부분이 모조리 삭제되었습니다.

다시 추가해 주세요

2021-09-02 09:20 UTC, abiriadev reviewed
Voice를 `음성` 으로 번역하는 것에 대해서 새로 이슈를 열거나 discussion을 열 필요가 있다고 봅니다.

2021-09-02 09:20 UTC, abiriadev commented on guide/whats-new.md
> +- [음성](/voice/): [`@discordjs/voice`](https://github.com/discordjs/voice) 패키지를 사용하도록 다시 짜였습니다
[Djs Voice](https://github.com/discordjs/voice) 는 그 자체로 고유명사처럼 쓰이고 있는데 굳이 `음성` 이라고 번역하는 것은 생소하게 느껴지지 않을까요?

2021-09-02 09:24 UTC, mswgen commented
@abiriadev 모든 문제 해결 끗!

2021-09-02 09:27 UTC, abiriadev reviewed
어떤 용어를 쓸 지에 대해 토론이 필요하다고 생각됩니다!

2021-09-02 09:27 UTC, abiriadev commented on guide/preparations/setting-up-a-linter.md
> +여러분이 ESLint를 사용하기 시작할 때, 여러분의 코드에서 엄청난 양의 에러와 경고를 보여줄 지도 모릅니다. 하지만 걱정하지 마세요. 일단 시작하기 위해, 여러분의 프로젝트 폴더 안에 `.eslintrc.json` 라는 파일을 만들고, 아래 코드를 복붙해주세요.
`복붙해주세요` 라는 용어가 과연 공식 문서에서 적합한지 잘 모르겠습니다! 😭

2021-09-02 09:28 UTC, abiriadev commented
마지막 토론이 남은 것 같아요! ^^

2021-09-02 09:30 UTC, mswgen commented on guide/preparations/setting-up-a-linter.md
> +여러분이 ESLint를 사용하기 시작할 때, 여러분의 코드에서 엄청난 양의 에러와 경고를 보여줄 지도 모릅니다. 하지만 걱정하지 마세요. 일단 시작하기 위해, 여러분의 프로젝트 폴더 안에 `.eslintrc.json` 라는 파일을 만들고, 아래 코드를 복붙해주세요.
엌
`복사해주세요`로 하죠.
복붙은 쫌...

2021-09-02 09:33 UTC, mswgen commented on guide/preparations/setting-up-a-linter.md
> +여러분이 ESLint를 사용하기 시작할 때, 여러분의 코드에서 엄청난 양의 에러와 경고를 보여줄 지도 모릅니다. 하지만 걱정하지 마세요. 일단 시작하기 위해, 여러분의 프로젝트 폴더 안에 `.eslintrc.json` 라는 파일을 만들고, 아래 코드를 복붙해주세요.
@abiriadev 끗

2021-09-02 09:36 UTC, merged

2021-09-03 02:01 UTC, mswgen commented
와 진짜 이렇게 긴거 처음이다ㅏㅏㅏㅏ

2021-09-03 12:25 UTC, mswgen reviewed
테스트